[custom]
; ==========================================================================================================================
; 000-Muti-ALL-NoDns-sblable-offline
; 解决DNS泄露，无分流群组
; tips:不支持负载均衡-轮询的策略定制,需要手动修改: strategy: consistent-hashing ==改为==> strategy: round-robin
; ==========================================================================================================================
; RuleSet
; ==========================================================================================================================
ruleset=🔰 Home手动选择,[]IP-CIDR,192.168.1.1/16,no-resolve
ruleset=🔰 github,[]DOMAIN-KEYWORD,github,no-resolve
ruleset=🔰 Gemini,[]DOMAIN,gemini.gstatic.com,no-resolve
ruleset=🔰 Gemini,[]DOMAIN,gemini.google.com,no-resolve
ruleset=🔰 Gemini,[]DOMAIN-KEYWORD,gemini,no-resolve
ruleset=⚖️ 负载均衡-轮询,[]DOMAIN-KEYWORD,youtube,no-resolve
ruleset=⚖️ 负载均衡-轮询,[]DOMAIN-KEYWORD,*youtube*,no-resolve

;http
ruleset=DIRECT,https://raw.githubusercontent.com/jimoying/ACL4SS/refs/heads/main/clash-rules/my-release/CustomDirect.list

ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL

; ==========================================================================================================================
; custom_proxy_group
; GROUPID = { 0:ak  1:hy2  2:merge }
; Format: Group_Name`url-test|fallback|load-balance`Rule_1`Rule_2`...`test_url`interval[,timeout][,tolerance]
; [外部配置](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E5%A4%96%E9%83%A8%E9%85%8D%E7%BD%AE)
; ==========================================================================================================================
#### 总选择 - 按优先级排序
;custom_proxy_group=🚀 节点选择`select`(.*)`[]⚖️ 负载均衡-轮询`[]⚖️ 负载均衡-散列`[]♻️ 自动选择`[]DIRECT`.*
;custom_proxy_group=🚀 节点选择`select`[]⚖️ 负载均衡-轮询`[]⚖️ 负载均衡-散列`[]♻️ 自动选择`[]DIRECT`.*
;custom_proxy_group=🚀 节点选择`select`[]⚖️ 负载均衡-轮询`[]⚖️ 负载均衡-散列`[]♻️ 自动选择`[]DIRECT`
;custom_proxy_group=🚀 节点选择`select`[]⚖️ 负载均衡-轮询`[]⚖️ 负载均衡-散列`[]♻️ 自动选择`♻️ github`[]DIRECT`.*
custom_proxy_group=🚀 节点选择`select`[]⚖️ 负载均衡-轮询.HK.merge`[]⚖️ 负载均衡-轮询.HK.hy2`[]⚖️ 负载均衡-轮询.HK.ak`[]⚖️ 负载均衡-轮询.JP.merge`[]⚖️ 负载均衡-轮询.JP.hy2`[]⚖️ 负载均衡-轮询.JP.ak`[]⚖️ 负载均衡-轮询.US.merge`[]⚖️ 负载均衡-轮询.US.hy2`[]⚖️ 负载均衡-轮询.US.ak`[]⚖️ 负载均衡-散列.HK.merge`[]⚖️ 负载均衡-散列.HK.hy2`[]⚖️ 负载均衡-散列.HK.ak`[]🔰 github`🔰 Gemini`🇺🇸 UnitedStates`[]🔰 Home手动选择`[]♻️ 手动选择`[]♻️ 自动选择`[]🛑 全球拦截 * 🎯 全球直连 * ⛔️ 广告拦截 * 🚫 运营劫持`[]DIRECT

#### 自定义策略组
; strategy: round-robin
; custom_proxy_group=⚖️ 负载均衡-轮询`load-balance`(香港|HK)`http://www.gstatic.com/generate_204`300,,50
; custom_proxy_group=⚖️ 负载均衡-散列`load-balance`.*`http://www.gstatic.com/generate_204`300,,50

; strategy: round-robin
custom_proxy_group=⚖️ 负载均衡-轮询.HK.merge`!!GROUPID=2!!(香港|HK)`[]DIRECT`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 负载均衡-轮询.HK.hy2`load-balance`!!GROUPID=1!!(香港|HK)`[]DIRECT`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 负载均衡-轮询.HK.ak`load-balance`(香港.*\{Ver10\}|香港.*\{ver10\})`[]DIRECT`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=⚖️ 负载均衡-轮询.JP.merge`load-balance`!!GROUPID=2!!(日本|JP)`[]DIRECT`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 负载均衡-轮询.JP.hy2`load-balance`!!GROUPID=1!!(日本|JP)`[]DIRECT`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 负载均衡-轮询.JP.ak`load-balance`(日本.*\{Ver10\}|日本.*\{ver10\})`[]DIRECT`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=⚖️ 负载均衡-轮询.US.merge`load-balance`!!GROUPID=2!!(美国|US)`[]DIRECT`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 负载均衡-轮询.US.hy2`load-balance`!!GROUPID=1!!(美国|US)`[]DIRECT`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 负载均衡-轮询.US.ak`load-balance`(美国.*\{Ver10\}|美国.*\{ver10\})`[]DIRECT`http://www.gstatic.com/generate_204`300,,50

; strategy: round-robin
custom_proxy_group=⚖️ 负载均衡-散列.HK.merge`load-balance`!!GROUPID=2!!(香港|HK)`[]DIRECT`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 负载均衡-散列.HK.hy2`load-balance`!!GROUPID=1!!(香港|HK)`[]DIRECT`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 负载均衡-散列.HK.ak`load-balance`(香港.*\{Ver10\}|香港.*\{ver10\})`[]DIRECT`http://www.gstatic.com/generate_204`300,,50

; 纯手动选择
;custom_proxy_group=♻️ github`url-test`.*`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=♻️ github`url-test`[]①香港??`[]②香港??`[]③香港??`[]④香港??`[]⑤香港??`[]GB_42`[]ss-yun-9pj2tu70`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=♻️ github`url-test`(①香港|②香港|③香港|④香港|⑤香港)`[]GB_42`[]ss-yun-9pj2tu70`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=♻️ github`select`(①香港|②香港|③香港|④香港|⑤香港)`(GB_42)`(ss-yun-9pj2tu70)`[]DIRECT
;custom_proxy_group=🔰 github`select`!!GROUPID=0!!(①香港|②香港|③香港|④香港|⑤香港)`(GB_42)`(ss-yun-9pj2tu70)`[]DIRECT
;不行,GROUPID=0会被GROUPID=1的节点给覆盖掉,而并非取的并集!!! ==> @deprecate ==> 可以,因为网络问题造成的原因! 是取的并集(链接1的节点 && 链接2的节点)
;custom_proxy_group=🔰 github`select`!!GROUPID=0!!([①,②,③,④,⑤]香港)`!!GROUPID=2!!(香港|HK)`(GB_42)`(p2p)`(ss-yun-9pj2tu70)`[]DIRECT
;正式
;custom_proxy_group=🔰 github`select`!!GROUPID=0!!([①,②,③,④,⑤]香港)`(GB_42)`(p2p)`(ss-yun-9pj2tu70)`[]DIRECT
custom_proxy_group=🔰 github`select`!!GROUPID=0-1!!(香港|HK|HKG)`(GB_42)`(p2p)`(ss-yun-9pj2tu70)`[]DIRECT


;失败!!! 1."?!"取反好像有问题  2.好像不支持3个及其以上"!!",最大支持2个"!!"
;custom_proxy_group=🔰 Gemini`select`!!GROUPID=2!!(香港|HK)!!((?!(.*Hong Kong 05)).*)`(GB_42)`(ss-yun-9pj2tu70)`[]DIRECT
custom_proxy_group=🔰 Gemini`select`!!GROUPID=2!!(Hong Kong 0[1-4])`(GB_42)`(p2p)`(ss-yun-9pj2tu70)`[]DIRECT

;数字金融/跨境电商
custom_proxy_group=🇺🇸 UnitedStates`select`(美国|US)`(GB_42)`(p2p)`(ss-yun-9pj2tu70)`[]DIRECT

custom_proxy_group=🔰 Home手动选择`select`[]DIRECT`(p2p)

custom_proxy_group=♻️ 手动选择`select`[]DIRECT`(.*)

; 纯自动选择: 超时自动切换(300,5,50--每隔300秒测试一次，测速超时为5s，切换节点的延迟容差为50ms)
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,5,50

; 拒绝
custom_proxy_group=🛑 全球拦截 * 🎯 全球直连 * ⛔️ 广告拦截 * 🚫 运营劫持`select`[]REJECT`[]DIRECT

; ========================================================================================================================== @ 使用`复杂正则` + 使用`特殊筛选条件` ==> 实际测试区域
;#### 测试-方式1-正则提取
;测试成功: 表示创建一个叫 节点选择 的 select 策略组,并向其中**依次**添加名字不包含'美国'或'日本'的节点
;custom_proxy_group=⚖️ 负载均衡-散列-测试555`load-balance`(^(?!.*(美国|日本)).*)`http://www.gstatic.com/generate_204`300,,50

;# 匹配整行 作为key!!! ==> 复杂正则表达式即匹配整行(复杂正则-匹配整行)
;\-- custom_proxy_group=⚖️ 负载均衡-散列-测试555`load-balance`(^(?!.*(美国|日本)).*)`http://www.gstatic.com/generate_204`300,,50

;# 匹配代理节点名字 作为key!!! ==> 简单正则表达式即匹配代理节点名字(简单正则-提取节点名字)
;\-- custom_proxy_group=⚖️ 负载均衡-轮询.HK.ak`load-balance`(香港.*\{Ver10\}|香港.*\{ver10\})`http://www.gstatic.com/generate_204`300,,50

;#### 测试-方式2-特殊筛选条件
;测试成功: 从添加的订阅链接中过滤第二条订阅链接中的香港节点
;custom_proxy_group=⚖️ 负载均衡-散列-测试444`load-balance`!!GROUPID=1!!(香港)`http://www.gstatic.com/generate_204`300,,50

; ==========================================================================================================================
enable_rule_generator=true
overwrite_original_rules=true

; ========================================================================================================================== @ 测试区域
#### 成功的正则表达式:
#### !!GROUPID=1!!(美国[1-4]号)
#### !!GROUPID=0!!([①,②,③,④]香港)
#### !!GROUPID=2!!(Hong Kong 0[1-4])