[custom]
; 解决DNS泄露，无分流群组
; ==========================================================================================================================
mixed-port: 7890
socks-port: 7891
port: 7892

; ==========================================================================================================================
;ruleset=♻️ github,[]DOMAIN-KEYWORD,github,no-resolve

;http
ruleset=♻️ github,http://192.168.81.183:8000/TestCustomDirect.list
;未测试成功!!!
;ruleset=♻️ github,./TestCustomDirect.list

;未测试成功!!!
;ruleset=!!import:snippets/rulesets.txt

ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL

; ==========================================================================================================================
;custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
;custom_proxy_group=🚀 节点选择`select`[]⚖️ 负载均衡-轮询`[]⚖️ 负载均衡-散列`[]♻️ 自动选择`[]DIRECT`.*
;custom_proxy_group=🚀 节点选择`select`[]⚖️ 负载均衡-轮询`[]⚖️ 负载均衡-散列`[]♻️ 自动选择`[]DIRECT`
custom_proxy_group=🚀 节点选择`select`[]⚖️ 负载均衡-轮询`[]⚖️ 负载均衡-散列`[]♻️ 自动选择`♻️ github`[]DIRECT`(香港|HK)

custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50

;自定义策略组
;custom_proxy_group=♻️ github`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ github`url-test`(香港|HK)`http://www.gstatic.com/generate_204`300,,50

;custom_proxy_group=⚖️ 负载均衡-轮询`load-balance`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 负载均衡-轮询`load-balance`(香港|HK)`http://www.gstatic.com/generate_204`300,,50

;custom_proxy_group=⚖️ 负载均衡-散列`load-balance`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 负载均衡-散列`load-balance`(香港|HK)`http://www.gstatic.com/generate_204`300,,50

; ==========================================================================================================================
enable_rule_generator=true
overwrite_original_rules=true